admin:
  access_log_path: /tmp/admin_access.log
  profile_path: /tmp/cpu.pprof
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 9901
static_resources:
  listeners:
  - name: listener_0
    address:
      socket_address:
        address: 127.0.0.1
        port_value: 10000
    filter_chains:
    - filters:
      - name: envoy.http_connection_manager
        config:
          stat_prefix: ingress_http
          codec_type: AUTO
          http_protocol_options:
            accept_http_10: true
            default_host_for_http_10: "metadata"
          server_name: GKE Metadata Server
          route_config:
            name: local_route
            virtual_hosts:
            - name: local_service
              domains: ["*"]
              routes:
              - match: { prefix: "/" }
                route: { cluster: metadata_service }
          http_filters:
          - name: mds_concealment
            config: {}
          - name: envoy.router
  clusters:
  - name: metadata_service
    connect_timeout: 0.25s
    type: STATIC
    lb_policy: ROUND_ROBIN
    hosts:
    - socket_address:
        address: 127.0.0.1
        port_value: 80
